### PR TITLE
PR: V0.2.0 release

### PR DESCRIPTION
**Pull request by tuopuu**
This PR is for the release version 0.2.0 of JYU-LB wrapper.

### CODE REVIEW

**Comment by tuopuu** [comment]
@nathanfranklin, please, take a look that this release PR is done properly.

**Comment by tuopuu** [comment]
Technically, I think, it should be merged _after_ simphony-common v0.2.2 has been released.

**Comment by nathanfranklin** [comment]
> Technically, I think, it should be merged after simphony-common v0.2.2 has been released.

yeah, that makes sense.

**Comment by tuopuu** [comment]
Merged now that simphony-commom v.0.2.2 is out.

**Pull request merged**
